### ISSUE TITLE
li class for CoprHD badge mislabled

### ISSUE THREAD

**Issue by JayCuthrell** [thecodeteam/codedellemc.github.io#63]
![screenshot 2015-07-06 at 8 21 45 am](https://cloud.githubusercontent.com/assets/95317/8525889/2cd74670-23b8-11e5-9dd7-2cc68e6af009.png)

**Comment by kacole2** [comment]
why is it mislabeled?

**Comment by JayCuthrell** [comment]
I noticed that the badge for CoprHR didn't appear to have any dialog appear in my browser. So, I assumed it should be "tooltip CoprHD tooltipstered". Then again the actual website didn't match what I saw in GitHub so maybe I'm just confused?

**Comment by kacole2** [comment]
it does not have a dialogue box appear because the link is pointing to http://coprhd.github.io/. I could change it to https://github.com/CoprHD/coprhd-controller and have the tooltip be exposed, but since github isn't the primary source for the code (read-only mirror), it's probably not the best idea at this time.

**Comment by JayCuthrell** [comment]
Roger that.
